server:
  port: 9050
  servlet.context-path: /account

spring:
  datasource:
    url: jdbc:postgresql://localhost:9000/lovable-account-db?sslmode=disable
    username: umang
    password: 12345
    driver-class-name: org.postgresql.Driver
