server:
  port: 9040
  servlet.context-path: /intelligence

spring:
  datasource:
    url: jdbc:postgresql://localhost:9000/lovable-intelligence-db?sslmode=disable
    username: umang
    password: 12345
    driver-class-name: org.postgresql.Driver
  
  ai:
    openai:
      api-key: ${OPENROUTER_API_KEY}
      base-url: https://openrouter.ai/api/v1
      chat:
        options:
          model: google/gemma-4-31b-it:free
