server:
  port: 9020
  servlet.context-path: /workspace

spring:
  datasource:
    url: jdbc:postgresql://localhost:9000/lovable-workspace-db?sslmode=disable
    username: umang
    password: 12345
    driver-class-name: org.postgresql.Driver
  
  data:
      redis:
        host: localhost
        port: 6379
minio:
  url: http://localhost:9100
  access-key: minioadmin
  secret-key: minioadmin123
  bucket: projects
  

    